name: campus_notes_app
description: "Campus Notes App - A comprehensive note sharing platform."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_app_check: ^0.4.1+2

  # State management
  provider: ^6.1.2

  # UI packages
  carousel_slider:
  shimmer: ^3.0.0
  flutter_staggered_animations:  ^1.1.0
  uuid: ^4.0.0
  file_picker: ^8.0.0   
  # Other utilities
  shared_preferences: ^2.2.2
  go_router: ^12.1.3
  crypto: ^3.0.7
  flutter_dotenv: ^6.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
